# This workflow will build a Java project with the maven wrapper

name: Java Build with Maven wrapper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: corretto
      - name: Build with Maven wrapper
        # env TZ: needed for unit tests with time to work correctly
        env:
          TZ: Europe/Amsterdam
        run: ./mvnw package
