# This workflow will build a Java project with the maven wrapper

name: Java Build with Maven wrapper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
      - name: Build with Maven wrapper
        # env TZ: needed for unit tests with time to work correctly
        env:
          TZ: Europe/Amsterdam
        run: ./mvnw package
