---
name: Release to maven central

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Show extracted Maven project version
        run: echo ${{ steps.project.outputs.version }}
      - name: Decode secrets file
        env:
          SECRETS_BUILD_SETTINGS_XML: ${{ secrets.SECRETS_BUILD_SETTINGS_XML }}
        run: echo "$SECRETS_BUILD_SETTINGS_XML" | base64 -d >> ./build-settings.xml
      - name: push snapshot to maven central
        if: contains(steps.project.outputs.version, 'SNAPSHOT') == true
        run: ./mvnw -s build-settings.xml clean javadoc:jar source:jar deploy
      - name: Close and release repository (NOT ACTIVE YET)
        if: contains(steps.project.outputs.version, 'SNAPSHOT') != true
        run: echo "RELEASE NOT SUPPORTED YET!"
      - name: Cleanup
        run: rm ./build-settings.xml
